### ISSUE TITLE
Artboard background color is wrong

### ISSUE THREAD

**Issue by daisukefuji** [SKAhack/open-sketch#1]
The original artboard background color was red. But it's white(no background color) after imported.

Sketch Version 40.3 (33839)
SKAhack/open-sketch.git 6e5613b2fee1245e7b65cd2c40d6fe443c6af9eb

<img width="802" alt="screen shot 2016-10-26 at 6 13 14 pm" src="https://cloud.githubusercontent.com/assets/3861209/19720188/1838ec50-9ba8-11e6-8420-46b363c5dfc4.png">

**Comment by skahack** [comment]
Fixed: https://github.com/SKAhack/open-sketch/commit/0dc4d9cb5c8e361d092ac2839a4d8008e751b236
Thank you for your report 🙇
