### ISSUE TITLE
Cannot export or import

### ISSUE THREAD

**Issue by debayangojek** [SKAhack/open-sketch#20]
> open-sketch@0.0.1 start /Users/debayansen/Projects/open-sketch
> npm run build && ./coscript main.js

> open-sketch@0.0.1 build /Users/debayansen/Projects/open-sketch
> browserify src/index.js | sed -E 's/\[function/[ function/g' | sed -E 's/`([^`]*)`/\1/g' > bundle.js

Running...
Exporting...
>>> Run Fri Aug 04 2017 14:54:51 GMT+0530 (IST)
/Applications/Sketch.app 46 44423
TypeError: null is not an object (evaluating 'app.window().isMiniaturized')
line: 1779
sourceURL: /Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 25
stack: /Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:1779:25
filter@[native code]
getActiveDocument@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:1778:19
main@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:970:37
/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:984:5
s@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:283
e@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:451
onRun@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:468

Importing...
>>> Run Fri Aug 04 2017 14:54:51 GMT+0530 (IST)
/Applications/Sketch.app 46 44423
TypeError: null is not an object (evaluating 'app.window().isMiniaturized')
line: 1779
sourceURL: /Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 25
stack: /Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:1779:25
filter@[native code]
getActiveDocument@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:1778:19
main@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:970:37
/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:984:5
s@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:283
e@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:451
onRun@/Users/debayansen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:7:468

**Comment by debayangojek** [comment]
After replacing `!app.window().isMiniaturized()` with `app.window() && !app.window().isMiniaturized()` I get more errors like: 

```
TypeError: this._layer.styleGeneric is not a function. (In 'this._layer.styleGeneric()', 'this._layer.styleGeneric' is undefined)
```

**Comment by skahack** [comment]
`open-sketch` project is deprecated since Sketch 43. Please read http://sketchplugins.com/d/87-new-file-format-in-sketch-43 . 
💭 ( I will add this notice to readme.md )

related projects:
- https://kactus.io/

**Comment by skahack** [comment]
readme updated
