### ISSUE TITLE
Does this use sketchtool for exporting

### ISSUE THREAD

**Issue by silentninja** [SKAhack/open-sketch#4]
Hey thanks for making this tool. Have you tried using the sketch tool for exporting the layers.
http://bohemiancoders.tumblr.com/post/89354240665/making-a-toolchain-not-just-a-tool

**Comment by skahack** [comment]
Thank you for your information. wow... I dont know this tool.
I guess `sketchtool dump [file]` is very useful and fast. I'll think this can use.
